name: 'GitHub Actions Versioner'
description: 'Checks if your GitHub Actions dependencies are up to date and suggests updates'
author: 'Mateusz Górniak'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
  workflow_path:
    description: 'Path to workflow files'
    required: true
    default: '.github/workflows'

outputs:
  outdated_actions:
    description: 'JSON array of outdated actions with their current and latest versions'
  status:
    description: 'Overall status of the check (success/failure)'

runs:
  using: 'node22'
  main: 'dist/index.js'
